#!/bin/bash

if [ "$(whoami)" != "zextras" ]; then
  echo "${0} must be run as user zextras"
  exit 1
fi

certonly() {
  if certbot "${@}" --dry-run; then
    certbot "${@}"
  fi
}

ACTION="${1}"

if [ "${ACTION}" = "certonly" ]; then
  certonly "${@}"
fi


