#!/bin/bash

if [ "$(whoami)" != "zextras" ]; then
  echo "${0} must be run as user zextras"
  exit 1
fi

certonly() {
  certbot "${@}" --dry-run
}

ACTION="${1}"

if [ "${ACTION}" = "certonly" ]; then
  certonly "${@}"
fi


