#!/bin/bash

# SPDX-FileCopyrightText: 2022 Synacor, Inc.
# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-2.0-only

source /opt/zextras/bin/zmshutil || exit 1
zmsetvars

find ${zimbra_tmp_directory} -maxdepth 1 -type f -mtime +7 -exec rm -f {} \; > /dev/null 2>&1
