#!/bin/bash

# SPDX-FileCopyrightText: 2022 Synacor, Inc.
# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-2.0-only

if [ "$(whoami)" != zextras ]; then
  echo "Error: must be run as zextras user"
  exit 1
fi

source /opt/zextras/bin/zmshutil || exit 1
zmsetvars -f

#
# Sanity checks
#
zmassert -x /opt/zextras/common/bin/mysqladmin
zmassert -x /opt/zextras/common/bin/mysql
zmassert -x /opt/zextras/bin/zmlocalconfig
zmassert -x /opt/zextras/bin/zmcontrol
zmassert -r ${zimbra_db_directory}/db.sql
if [ ! -x /opt/zextras/common/bin/mysql ]; then
  echo "Mysql not found on this host."
  exit 1
fi

usage() {
  echo "$0 [-help] password"
}

ask() {
  PROMPT=$1
  DEFAULT=$2

  echo ""
  echo -n "$PROMPT [$DEFAULT] "
  read response

  if [ -z $response ]; then
    response=$DEFAULT
  fi
}
askYN() {
  PROMPT=$1
  DEFAULT=$2

  if [ "x$DEFAULT" = "xyes" -o "x$DEFAULT" = "xYes" -o "x$DEFAULT" = "xy" -o "x$DEFAULT" = "xY" ]; then
    DEFAULT="Y"
  else
    DEFAULT="N"
  fi

  while [ 1 ]; do
    ask "$PROMPT" "$DEFAULT"
    response=$(perl -e "print lc(\"$response\");")
    if [ -z $response ]; then
      :
    else
      if [ $response = "yes" -o $response = "y" ]; then
        response="yes"
        break
      else
        if [ $response = "no" -o $response = "n" ]; then
          response="no"
          break
        fi
      fi
    fi
    echo "A Yes/No answer is required"
  done
}

for opt in "$@"; do
  case "$opt" in
    -help | --help | -h | --help)
      usage
      exit 0
      shift
      ;;
    --* | -*)
      echo "Unknown option $opt"
      usage
      exit 1
      shift
      ;;
    *)
      password=$1
      shift
      ;;
  esac
done

if [ x"$password" = "x" ]; then
  usage
  exit 1
fi

askYN "WARNING: All zimbra services will be stopped.  Would you like to continue?" "N"
if [ $response != "yes" ]; then
  echo "All services must be stopped in order to reset mysql password. Exiting."
  exit
fi

/opt/zextras/bin/zmcontrol stop

echo "Starting mysqld"
/opt/zextras/common/bin/mysqld_safe --defaults-file=${mysql_mycnf} --skip-grant-tables --ledir=/opt/zextras/common/sbin &
sleep 10

echo "Changing zextras passwd"
/opt/zextras/bin/mysql -Dmysql -P ${mysql_port} -e "update user set password=PASSWORD(\"$password\") where user = 'zextras';"
/opt/zextras/bin/zmlocalconfig -f -e zimbra_mysql_password=$password

echo "Changing root passwd"
/opt/zextras/bin/mysql -Dmysql -P ${mysql_port} -e "update user set password=PASSWORD(\"$password\") where user = 'root';"
/opt/zextras/bin/zmlocalconfig -f -e mysql_root_password=$password

echo "Flushing privileges"
/opt/zextras/bin/mysql -Dmysql -P ${mysql_port} -e "flush privileges;"
/opt/zextras/bin/mysql.server stop

echo "Restarting carbonio services"
/opt/zextras/bin/zmcontrol start
