#!/bin/bash

# SPDX-FileCopyrightText: 2022 Synacor, Inc.
# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-2.0-only

if [ ! -f /.dockerenv ]; then
  ulimit -n 32768
  ulimit -c unlimited
  ulimit -v unlimited
fi
exec /opt/zextras/common/libexec/slapd "$@"
