#!/bin/bash

# SPDX-FileCopyrightText: 2022 Synacor, Inc.
# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-2.0-only

umask 027
source /opt/zextras/bin/zmshutil || exit 1
zmsetvars

if [ ! -x /opt/zextras/common/sbin/slapcat ]; then
  exit 0
fi

u=$(id -un)
if [ $u != ${zimbra_user} ]; then
  echo "Error: must be run as ${zimbra_user} user"
  exit 1
fi

if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
  echo "USAGE: Exports LDAP databases"
  echo "Main database: zmslapcat <DIR>"
  echo "Config database: zmslapcat -c <DIR>"
  echo "Accesslog database: zmslapcat -a <DIR>"
  exit 1
fi

D=$(date +%Y%m%d%H%M%S)
CONFIG=no
FILE=ldap.bak.${D}
NFILE=ldap.bak
if [ x$1 = "x-c" ]; then
  CONFIG=yes
  FILE=ldap-config.bak.${D}
  NFILE=ldap-config.bak
  DEST=$2
elif [ x$1 = "x-a" ]; then
  ALOG=yes
  FILE=ldap-accesslog.bak.${D}
  NFILE=ldap-accesslog.bak
  DEST=$2
else
  DEST=$1
fi

mkdir -p $DEST
RC=0
if [ x$CONFIG = "xyes" ]; then
  /opt/zextras/common/sbin/slapcat -F /opt/zextras/data/ldap/config -n 0 -l ${DEST}/${FILE}
  RC=$?
elif [ x$ALOG = "xyes" ]; then
  if [ -d /opt/zextras/data/ldap/accesslog/db ]; then
    /opt/zextras/common/sbin/slapcat -F /opt/zextras/data/ldap/config -b "cn=accesslog" -l ${DEST}/${FILE}
    RC=$?
  else
    exit $RC
  fi
else
  /opt/zextras/common/sbin/slapcat -F /opt/zextras/data/ldap/config -b "" -l ${DEST}/${FILE}
  RC=$?
fi

cp -f ${DEST}/${FILE} ${DEST}/${NFILE}
exit $RC
